### ISSUE TITLE
sort order for email#index view

### ISSUE THREAD

**Issue by arossback** [themarshallproject/pony#2]
should this sort by updated_at?

**Comment by arossback** [comment]
@ivarvong before i merge, can you confirm this hotfix has been tested?

**Comment by ivarvong** [comment]
I'll PR against `develop` so it deploys to the staging server.

**Comment by ivarvong** [comment]
Deployed to https://pony-demo-develop.herokuapp.com/new-session/demo, you can see my "updated third" email is at the top of the "updated two" one.
